### ISSUE TITLE
Could you plz share your training weights(or set the default expire time of the dataset url much longer)?

### ISSUE THREAD

**Issue by cuirq3** [pubgeo/monocular-geocentric-pose#1]
I'm trying to download your extended US3D dataset from ieee dataport.
But the dataset files' default urls are set to be expired within 24 hours. I can't finish downloading in that short time.
And if I use S3 to try to download, it tells me _Access Denied_. (maybe because I didn't subscribe to ieee dataport)
So, if possible, could you share your weights or change that default time setting?
Thanks!

**Comment by pubgeo** [comment]
I think there are two issues here. One is that we neglected to post the weights at all. Thanks for the reminder to do that. We're doing it now on the GitHub repo, so that should be up soon. The other issue is downloading data from DataPort. The timeout for HTTP download isn't something we have any control over - and uploading that way was also challenging. Since the repo is Open Access, you should be able to download using S3 using the credentials indicated on the DataPort page. Under "dataset files" on that page, click "AWS S3" and then "view AWS security credentials". The page that comes up will have the AWS access key id and the secret access key. You'll need both to access the data. I'll leave this open for now. Please let us know if this works for you and then we'll close it.

**Comment by cuirq3** [comment]
Thank you for your quick reply!
I think I will wait for your weights.
About using the AWS S3 way, I got to know something from this website:
https://ieee-dataport.org/help/accessing-ieee-dataport-dataset-files-through-amazon-web-services-aws
![image](https://user-images.githubusercontent.com/50020459/86987201-0a617300-c1c8-11ea-968b-474f6dffe803.png)
It needs to subscribe to IEEE DataPort which costs $40/month, that's why my account doesn't own AWS security credentials. It should work if I subscribe to it.
Thanks for your help :)

**Comment by pubgeo** [comment]
Just noticed I didn't respond and close this issue after Gordon posted the weight files. Closing this issue now.

**Comment by yiying66** [comment]
Hi, where can I download  the weight files?  I didn't find it in the project page.

**Comment by gordonac** [comment]
They can be found in the releases [here](https://github.com/pubgeo/monocular-geocentric-pose/releases/tag/paper).

**Comment by lauraset** [comment]
Hi @cuirq3 , have you downloaded the dataset using aws3? Can you share it by Baiduyun storage app? Thank you in advance.

**Comment by cuirq3** [comment]
> Hi @cuirq3 , have you downloaded the dataset using aws3? Can you share it by Baiduyun storage app? Thank you in advance.

Sorry, I'm not working on this anymore and didn't try to download it since my last post.

**Comment by lauraset** [comment]
Thank you any way.
