### ISSUE TITLE
The relationship between height and magnitude.

### ISSUE THREAD

**Issue by yiying66** [pubgeo/monocular-geocentric-pose#4]
Hi, 
    Thank you for your excellent work !
    I am confused about the relationship between height and magnitude and how to transform height to magnitude.
    Looking forward to your reply！

**Comment by gordonac** [comment]
If you take a look at utilities/misc_utils.py line 53 you'll see the relationship. `mag = agl * vflow_data["scale"]`, where agl represents above ground level (AGL) heights. The scale factor in the VFLOW json files can be used to convert between height and magnitude.

**Comment by yiying66** [comment]
Thanks reply. I have another question. How do you get the data "scale". I mean is this calculated by yourself in some way or provided by DTM， DSM or something else（I am not very familiar with satellite maps and remote sensing）?

**Comment by pubgeo** [comment]
Because the sensor is hundreds of thousands of meters away, we can approximate the satellite imaging sensor model locally as affine, and affine projection satisfies two useful properties. First, rays are parallel (focal length is infinite), which allows us to calculate a single orientation angle in the image plane that defines "up" - height flows along that direction only. Second, length ratios are invariant along the parallel rays, allowing us to calculate a single scale factor relating magnitude in pixels and height in meters. These calculations do not require a DSM or DTM. They only require that we approximate the affine projection centered on a world coordinate that is in the right ballpark, but it does not need to be accurate. We get a rough approximation of the center coordinate from the image metadata and approximate the model with pseudo control points sampled around that point.
