### ISSUE TITLE
How to transform building annotations to footprints?

### ISSUE THREAD

**Issue by progressforever** [pubgeo/monocular-geocentric-pose#5]
Thanks for your excellent working!
I have some questions about building footprint extraction.  I want to konw how can i transform building annotations to footprints on my own data without training.
I am interested in how to transform building annotations to footprints, But I can not find the related code about it. Can you open source related code of this part？
Thanks a lot~  Looking forward for your early reply~

**Comment by gordonac** [comment]
This isn't in the repository now, but the code for the experiments in the paper is very simple. We created a new empty footprints image (say `F`), and for each pixel in the building ground truth (facades+roof, say `B_gt`), we set the pixel of the new location in F (based on the predicted VFLOW vector) to 1. So something like `F[y+VFLOW[y,x,0], x+VFLOW[y,x,1]] = B_gt[y, x] if B_gt[y,x]==1`. The method was used for the paper because of its simplicity, and because it more directly measured the contribution of the VFLOW predictions as opposed to any subsequent post-processing that might need to add.
